dist: xenial

language: node_js
node_js:
  - 12.14.1

cache:
  yarn: true

env:
  global:
    - PATH="$HOME/.yarn/bin:$PATH"
    - YARN_VERSION="1.9.4"
    # NODE_ENV:
    - secure: "ii2XIlDeeSCzKlTpBoZdFkVQiHdF4hbEL74ITSwkmi/nbxg9Nq7nKi9FdhhxF1EegdehTaYi7zfSipx9F+TnNZRe2AEqy9efZLhRHqtY8nojtH9ldecL0jC0SV/uJQ1xigOU3SXHcWV5wpd7DDS5URUVhsDGe4E+o+KBAKzadmNdohjG80FZ8AdgmUxbTMjJV7yhGd35g2SAaHWoFWVnMfckkBlUbqr+JmuxqbJwQ+Lmu8b3PYh+qYolW7lnUe73mbD5oKi1jgBnAuk82VVhGL7VaAVd2BgXQCbejBxDRhwl0Aty0mYYqbbq5LkioY1uDpQ4hCEh9V7Oo77qdkwBbiyP17lY6A3W0c4MDu8vqzecWYMtlzFLPJ5vT1Qin+LywHjCEGSGAfo4m0dVdMuuzKLp6Wrtfcc/2KuwEiLiucmFHjYWhnBIJpuhCIFpFLbVXMrJyuzrxvxD965qIhaxTSs3cvgha+DVZXe+s8pHp2sajG8Iwvpn3T3ISXoT6xoW7brRpA50Zlcj5W0o/coOiLtQP/u6n09BtB6tkyJpFyQB6qvdX2c+gK+Va7+vFVgiVvASHRWTNW8cvBZYEBn/iva/h5MP5CorPXWTSRlvHtXXWxpLE+p7BeecwKEzyvOQVqePfshdqGgrxPyINyg4WIVmuVjKc/mvaUhNfQPTKyE="

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "${YARN_VERSION}"

install: yarn install --frozen-lockfile

jobs:
  include:
    # Install dependencies and save them to the Travis cache
    - stage: "Prepare cache"
      # Don't run `script`, just install dependencies
      before_script: true
      script: true
    # Run tests
    - stage: "Test"
      name: "Lint"
      script:
      # Lint this package using this package. How meta.
      - yarn link
      - yarn link eslint-plugin-goodeggs
      - yarn run lint
    - name: "Unit Tests"
      script: yarn run test:unit
    - stage: "Publish to registry"
      if: tag =~ ^v
      script: echo "Publishing to npm registry..."
      deploy:
        provider: npm
        email: open-source@goodeggs.com
        api_key: $NPM_AUTH
        skip_cleanup: true
        on:
          all_branches: true
