dist: xenial

language: node_js
node_js:
  - 12.14.1

cache:
  yarn: true

env:
  global:
    - PATH="$HOME/.yarn/bin:$PATH"
    - YARN_VERSION="1.9.4"
    # NPM_AUTH:
    - secure: "EQnTLjwiRViFomQIiyNnme/oh782EZgstOBgTfAZoEhPHCmKSZocHlRnBEgj5o6mG1EAihRgyAFF/GSNQkHWB/w68MDx6GOib/+n2TmE8DzNv+6vYBUJTrNOmc58cDl/bvGwDLcohq942DJKcjjsJbpMmQzcmxc63iKtb94rPRxZvkLgyG+NKzUcHRWof8H59p+jiNO/YrGkKsWCeNIErzE/kWAClZ8LQm4TQee7E0t2O/BESYfEg4FkMN0Kk6eUa32lQTVQrWOHkn5a8Yk+OpAHpN6UP5VacdxUcgdG+COMdRd0cZgLV0epO2frlPS2ofWNgQGdnIilhqBhmLPtN73xFH6vRpTCXKi3pAnoaxGSfbbOqnYBnRzOIpjXeGH8GAHbn9SqEt/3+EVgHVgrjmhY1mglCJLvjc3U+7or5Tt8kITgYqmCoLAMGyfcFe8BoXkzv3OaI5+28Cfg2hKPgW5HHt5IbF1LUfAc6VgIXeFD+NJSl7u3bVCPr0ydJZoL4ddlexeQ1VlLuclx7p+LquSehg1pJJ5V9GlbQacLVNhVoSYt2ZnsnK8iH4jT9uGXFGeatTh4BOLpQOvTWCABmCufxOLv3ykKFrzeRHFtoPQUGfgZR+cKgVxlIIoof/UNdvV6mwBgiCwTdDV8V5wRUCV14zpasQzuPJumb33AV0U="

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "${YARN_VERSION}"

install: yarn install --frozen-lockfile

jobs:
  include:
    # Install dependencies and save them to the Travis cache
    - stage: "Prepare cache"
      # Don't run `script`, just install dependencies
      before_script: true
      script: true
    # Run tests
    - stage: "Test"
      name: "Lint"
      script:
      # Lint this package using this package. How meta.
      - yarn link
      - yarn link eslint-plugin-goodeggs
      - yarn run lint
    - name: "Unit Tests"
      script: yarn run test:unit
    - stage: "Publish to registry"
      if: tag =~ ^v
      script: skip
      deploy:
        provider: npm
        email: open-source@goodeggs.com
        api_key: $NPM_AUTH
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
