dist: bionic

language: node_js
node_js:
  - 12.14.1

cache:
  yarn: true

env:
  global:
    - PATH="$HOME/.yarn/bin:$PATH"
    - YARN_VERSION="1.9.4"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "${YARN_VERSION}"

install: yarn install --frozen-lockfile

jobs:
  include:
    # Install dependencies and save them to the Travis cache
    - stage: "Prepare cache"
      # Don't run `script`, just install dependencies
      before_script: skip
      script: skip
    # Run tests
    - stage: "Test"
      name: "Lint"
      script:
      # Lint this package using this package. How meta.
      - yarn link
      - yarn link eslint-plugin-goodeggs
      - yarn run lint
    - name: "Unit Tests"
      script: yarn run test:unit
    - stage: "Publish to registry"
      if: tag =~ ^v
      script: skip
      deploy:
        provider: npm
        email: open-source@goodeggs.com
        api_token:
          secure: "VNNUgqm9whQadtrrHtzUS1sigzMmCkDNMpHCAmAocYPgaoKScdITRrL35tNxyB4pER4WAuSSrqGdsxi8G96uo7/SU3o1UkvD2dV/FRLAVUcjhp5995A3Ah5UH0D/6mEA4PZQC0e0kjOcFpLtpB8OMhyrQto1NjNdFyZg9k1/xbOdoUDRbz/YXd4mB5arxEui0wKbGcYYk4y8Abp3aHuKdJVtI8VbtdBOJZn+aXfh+wlGJzeD62AUT26nzm1VTnGPYAoF02YGL//IXp0/ddy5D+0hGaKeD1aLwY1wkf6qiKFqaMVUGbeUW140vtblxBQZfpGo77PPOk1z9zy0ZxBbI0pIaQnAeep8neAi6hfcs9SRHA/5oNSBdq+u2TmzAqdvGRWhNEs+M62ji7HCSmi7LUeM1hBx6yUlD1OEnP3HSBlT5ZKByqHlmtYXFZ+BBape6jX9GvQrAwwyq6C64hQDHhwNN3mTpeBwVRXN3fX5sv9u68NYP4eOy8djm3+jX0m4I/+cFEe2ZUmkNrOBvY2D3hs5ITIQjfkHRDt8UEPNsxn2+jBhQgtJFCiRyydqOzTTNzGCRtfmcYNb7i71k4/WhJOG9p6L1BzeoZERCmx66SGDwwgwxzEC7BKxZwNlIa9U5fT8N7mRiSFAZDBf6UWGa4ADZcGUVHVms1BbgNkiRXc="
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
