dist: bionic

language: node_js
node_js:
  - 12.22.12

cache:
  yarn: true

env:
  global:
    - PATH="$HOME/.yarn/bin:$PATH"
    - YARN_VERSION="1.9.4"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "${YARN_VERSION}"

install: yarn install --frozen-lockfile

jobs:
  include:
    # Install dependencies and save them to the Travis cache
    - stage: "Prepare cache"
      # Don't run `script`, just install dependencies
      before_script: skip
      script: skip
    # Run tests
    - stage: "Test"
      name: "Lint"
      script:
      # Lint this package using this package. How meta.
      - yarn link
      - yarn link eslint-plugin-goodeggs
      - yarn run lint
    - name: "Unit Tests"
      script: yarn run test:unit
    - stage: "Publish to registry"
      if: tag =~ ^v
      script: skip
      deploy:
        provider: npm
        email: open-source@goodeggs.com
        api_token:
          secure: "EYTvota0/hOLW6hw/GZAaBpdy8UsQFGFEY2z80sl46MFocQaIA7S6VRYgtkja0epzsEapY9eSAfUaMz8oOmLsNRK2ZFmfmu2H6t6XaetP96D/2oMWTvNG8X9+MghWUbbKcHIzmbQ+S33Nja/OgrVxxlNfUL0Uuy+/HmrF07p7M1YVuKu7rHo86do438AFtz6FF8hYzlr6M7UdkPjr1WNMal60XHbHI9GstezfRkJtgKkxO2pCkLvgx/5MIcqGNeAa3azNcC1mAsum5AVnafaZCCMcEFUlnCk/3Wt6Sbc8ttI3Rsh8ifvitU0dyKCx7r9Vmum6ZrmZldbqRZtYxO7bdb6z8Ukmz+2q5U+JZwSRv8OpwT2hVeuxGsTWbqO9CBGyfsXgzBaYLoRlkXOkK1FmyfxUDocVBUWC1sIKW8hlMscmUG07F6YQYWGgHGUqgurU6C+OjwroOzbapEr4XoswUkNPWhxRRvpldrKyV3uUy1tjWyXkvU8ZsbjvV973ko40U4BOC4jCdWxBZCee41awm5Q0F5UWU5pOgaRj50nhP+Dcf8WFHnegdBwlfMhVR7KjBwDdLPH1sloT3zv/Ebw2ldMcjmDUwt0UMP2TfzuO2oEwkmDuYR/7f5xoW5bj5ZoVmOHoHaMEsC+XsxjhGWFl0hmztizSG3m7xNfVUq/jeA="
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
