dist: xenial

language: node_js
node_js:
  - 12.14.1

cache:
  yarn: true

env:
  global:
    - PATH="$HOME/.yarn/bin:$PATH"
    - YARN_VERSION="1.9.4"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "${YARN_VERSION}"

install: yarn install --frozen-lockfile

jobs:
  include:
    # Install dependencies and save them to the Travis cache
    - stage: "Prepare cache"
      # Don't run `script`, just install dependencies
      before_script: skip
      script: skip
    # Run tests
    - stage: "Test"
      name: "Lint"
      script:
      # Lint this package using this package. How meta.
      - yarn link
      - yarn link eslint-plugin-goodeggs
      - yarn run lint
    - name: "Unit Tests"
      script: yarn run test:unit
    - stage: "Publish to registry"
      if: tag =~ ^v
      script: skip
      deploy:
        provider: npm
        email: open-source@goodeggs.com
        api_token:
          secure: "Cmmf8sYQFtbMi7NDGDqLZBs7Nv6hIadkDf7LomuFxsLu3u/ZUd7OWwdA6lDGXJw7Q+tNoofcl9YRnWBH0kCmmznR9YKZfwU+8CLLD8gaaaH0Pb8PmJBFRakv9G3CrFLHDY4iZK4sHyKsUtE/hMWh2gg88esbN9IRIEBMy2oHfEs9gj37Q+5QKK8RctUuBIA34xLNVB3dU59+a/Fifjysdl7CnyFNqvGPlVRZIhlGl2HT3FgZCrNH0NaRWCZ7YMsSByfyoGmGusEjyEYDo6T+a6bMAXUM+quODPZlUyeBweJ8k7HmFgSZly4omFQQRRHcKtm2z5N7ilRvoyF0jtTEDutTSDAwcv8wjU8k/ZPWpGoqleHovjAiI2C6XQFByHC5NzE/ayX4Cuk7V/uecIREj+RXP4WcR3EFOjf65kvuq5JUgj+TpmgjUSpm+13WQW5C4ok8ROX7wybqewfjvvFjtQZBKqCwUzv9UwzR51+JZGYd0yYrdcnUOXD3nrJqeqfFAUqlkxVJoZ5mWL0+O/6ZfP/Kib1/s6zej4TtOoWeP51G9UKSSTdlT9PglqIuzGhIHQ0QceOXAt1t5k45dEp+vHat/rT9Jf0B9IN2ysr4mqIDIoMUDLktiS4baMheVzLXjD9qc9AxqAKeufaHDF/4bTTd4+4Mqk6Yxm3XTljDD84="
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
